SET check_function_bodies = false;
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('currency', '多國貨幣模組', NULL, NULL);
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('invoice', '電子發票模組', NULL, NULL);
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('locale', '多國語系模組', NULL, NULL);
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('search', '搜尋模組', NULL, NULL);
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('social_connect', '社群綁定模組', NULL, NULL);
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('permission', '權限模組', NULL, NULL);
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('customer_review', '評價模組', NULL, NULL);
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('creator_display', '創作者展示模組', NULL, NULL);
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('xuemi_pt', '學米私塾課模組', NULL, NULL);
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('sms_verification', '簡訊驗證', NULL, NULL);
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('line', 'LINE模組', NULL, NULL);
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('craft_page', '模板頁面模組', NULL, NULL);
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('xuemi', 'permission', NULL, NULL);
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('coin', '代幣模組', NULL, '行銷推廣');
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('coupon_scope', '折抵範圍模組', NULL, '行銷推廣');
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('member_card', '會員卡模組', NULL, '行銷推廣');
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('point', '點數紅利模組', NULL, '行銷推廣');
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('voucher', '兌換券模組', NULL, '行銷推廣');
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('sharing_code', '推廣模組', NULL, '行銷推廣');
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('referrer', '推薦模組', NULL, '行銷推廣');
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('group_buying', '團購模組', NULL, '行銷推廣');
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('learning_statistics', '學習成效模組', NULL, '客戶關係');
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('member_note', '備註模組', NULL, '客戶關係');
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('member_property', '自訂欄位模組', NULL, '客戶關係');
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('member_task', '任務模組', NULL, '客戶關係');
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('member_assignment', '會員分派模組', NULL, '客戶關係');
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('attend', '打卡模組', NULL, '客戶關係');
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('member_rejection', '學員拒絕模組', NULL, '客戶關係');
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('member_note_demo', '預約聯絡紀錄模組', NULL, '客戶關係');
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('learning_statistics_advanced', '學習分析模組', NULL, '客戶關係');
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('commonhealth_login', '康健登入模組', NULL, '第三方登入');
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('contract', '合約模組', NULL, NULL);
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('sku', '料號模組', NULL, NULL);
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('sales', '業務模組', NULL, NULL);
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('private_activity', '私密活動模組', NULL, '內容變現');
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('permission_group', '權限組模組', NULL, NULL);
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('group_buying_ticket', '多人購票模組', NULL, NULL);
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('transfer_voucher', '兌換券轉贈模組', NULL, NULL);
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('vital_crm', 'Vital客戶管理系統模組', NULL, NULL);
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('cw_login', '天下登入模組', NULL, '第三方登入');
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('program_content_external_file', '外部檔案模組', NULL, NULL);
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('coin_back', '回饋金模組', '只有啟用代幣模組才有效', '行銷推廣');
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('project_auto_delivery', '專案自動交付', '', NULL);
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('search_advanced', '進階搜尋模組', NULL, NULL);
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('sale_voucher', '兌換方案銷售', '可以銷售兌換方案', NULL);
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('spgateway', '藍新金流模組', NULL, '金流');
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('analysis', '數據分析模組', NULL, NULL);
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('certificate', '證書模組', '', NULL);
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('activity', '活動模組', NULL, '內容變現');
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('appointment', '預約模組', NULL, '內容變現');
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('approval', '審核模組', NULL, '內容變現');
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('blog', '部落格模組', NULL, '內容變現');
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('merchandise', '商品模組', NULL, '內容變現');
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('podcast', '廣播模組', NULL, '內容變現');
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('podcast_recording', '廣播錄音模組', NULL, '內容變現');
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('program_package', '課程組合模組', NULL, '內容變現');
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('project', '專案模組', NULL, '內容變現');
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('qrcode', 'QR碼模組', NULL, '內容變現');
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('tempo_delivery', '節奏交付模組', NULL, '內容變現');
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('merchandise_customization', '商品客製模組', NULL, '內容變現');
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('merchandise_virtualness', '商品虛擬模組', NULL, '內容變現');
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('order_contact', '出貨聯絡模組', NULL, '內容變現');
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('practice', '作業模組', NULL, '內容變現');
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('program_content_material', '課程教材模組', NULL, '內容變現');
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('exercise', '測驗模組', NULL, '內容變現');
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('private_appointment_plan', '私密預約方案模組', NULL, '內容變現');
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('activity_online', '線上直播活動模組', NULL, '內容變現');
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('zoom', 'Zoom 模組', NULL, NULL);
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('fb_pixel', 'FB Pixel 模組', NULL, '行為追蹤');
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('ga', 'Google Analytics 模組', NULL, '行為追蹤');
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('gtm', 'Google Tag Manager 模組', NULL, '行為追蹤');
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('hotjar', 'Hotjar 模組', NULL, '行為追蹤');
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('tappay', 'TapPay 模組', NULL, '金流');
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('private_program_package', '私密課程組合模組', NULL, '內容變現');
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('parenting', '親子天下金流模組', NULL, '金流');
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('paypal', 'PayPal 模組', NULL, '金流');
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('line_login', 'Line 登入模組', NULL, '第三方登入');
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('google_login', 'Google 登入模組', NULL, '第三方登入');
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('fb_login', 'Facebook 登入模組', NULL, '第三方登入');
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('commonhealth', '康健金流模組', NULL, '金流');
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('parenting_login', '親子天下登入模組', NULL, '第三方登入');
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('academic_affairs', '教務模組', NULL, NULL);
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('atome', 'Atome 模組', NULL, '金流');
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('question_library', '題庫模組', NULL, NULL);
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('sms', '簡訊發送', '可發送簡訊給學員', NULL);
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('venue', '場地模組', NULL, NULL);
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('exam', '測驗模組', NULL, 'program');
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('customScript', '自訂腳本', NULL, NULL);
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('gift', '贈品方案模組', NULL, NULL);
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('class_order', '入退班', NULL, NULL);
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('ecpay', '綠界金流模組', NULL, NULL);
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('project_role', '專案角色管理模組', NULL, NULL);
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('line-notify', 'LineNotify模組', NULL, NULL);
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('login_restriction', '登入上限模組', NULL, NULL);
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('portfolio_project', '作品專案模組', NULL, NULL);
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('school', '學校學區模組', NULL, NULL);
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('device_management', '裝置管理模組', NULL, NULL);
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('member_info_export', '會員資料匯出', NULL, NULL);
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('timetable', 'timetable', NULL, NULL);
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('business_member', '公司管理模組', NULL, NULL);
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('meet-service', 'MeetService模組', NULL, NULL);
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('channel_sku', '通路料號模組', NULL, NULL);
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('background_mode', '背景播放模組', NULL, NULL);
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('meet_service', 'MeetService模組', NULL, NULL);
INSERT INTO public.module (id, name, abstract, category_name) VALUES ('openai', 'Open AI', NULL, NULL);
