version: "3.6"

x-redis: &redis
  image: redis:latest
  ports:
    - 127.0.0.1:6379:6379
  restart: always

x-postgres: &postgres
  image: postgres:latest
  ports:
    - 127.0.0.1:5432:5432

x-mongo: &mongo
  image: mongo:latest
  ports:
    - 127.0.0.1:27017:27017

x-pgadmin: &pgadmin
  image: dpage/pgadmin4
  ports:
    - 127.0.0.1:5050:80
  environment:
    PGADMIN_DEFAULT_EMAIL: admin@admin.com
    PGADMIN_DEFAULT_PASSWORD: root

x-mongo-express: &mongo-express
  image: mongo-express:latest
  ports:
    - 127.0.0.1:5051:8081

x-hasura: &hasura
  image: hasura/graphql-engine:v2.22.0
  ports:
    - 127.0.0.1:8080:8080
  restart: always

services:
  redis-test:
    <<: *redis
    profiles: ["test", "all"]
    command: redis-server --requirepass test-redis-passwd

  redis-dev:
    <<: *redis
    profiles: ["dev", "all"]
    command: redis-server --requirepass dev-redis-passwd

  postgres-test:
    <<: *postgres
    profiles: ["test", "all"]
    environment:
      POSTGRES_DB: 'test'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: '1234'

  postgres-dev:
    <<: *postgres
    profiles: ["dev", "all"]
    environment:
      POSTGRES_DB: 'dev'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: '1234'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - postgresdb:/var/lib/postgresql/data

  mongo-test:
    <<: *mongo
    profiles: ["test", "all"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'test'
      MONGO_INITDB_ROOT_PASSWORD: '1234'
      MONGO_INITDB_DATABASE: 'test'

  mongo-dev:
    <<: *mongo
    profiles: ["dev", "all"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'dev'
      MONGO_INITDB_ROOT_PASSWORD: '1234'
      MONGO_INITDB_DATABASE: 'dev'

  pgadmin-test:
    <<: *pgadmin
    profiles: ["test", "all"]
    depends_on:
      - postgres-test

  pgadmin-dev:
    <<: *pgadmin
    profiles: ["dev", "all"]
    depends_on:
      - postgres-dev

  mongo-express-test:
    <<: *mongo-express
    profiles: ["test", "all"]
    depends_on:
      - mongo-test
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://test:1234@mongo-test:27017
      ME_CONFIG_MONGODB_AUTH_DATABASE: test
      ME_CONFIG_BASICAUTH_USERNAME: test
      ME_CONFIG_BASICAUTH_PASSWORD: 1234

  mongo-express-dev:
    <<: *mongo-express
    profiles: ["dev", "all"]
    depends_on:
      - mongo-dev
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://dev:1234@mongo-dev:27017/dev
      ME_CONFIG_MONGODB_AUTH_DATABASE: dev
      ME_CONFIG_BASICAUTH_USERNAME: dev
      ME_CONFIG_BASICAUTH_PASSWORD: 1234

  hasura-test:
    <<: *hasura
    profiles: ["test", "all"]
    environment:
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DATABASE_URL: postgres://user:1234@postgres-test:5432/test
      PG_DATABASE_URL: postgres://user:1234@postgres-test:5432/test
    depends_on:
      - postgres-test

  hasura-dev:
    <<: *hasura
    profiles: ["dev", "all"]
    environment:
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DATABASE_URL: postgres://user:1234@postgres-test:5432/dev
      PG_DATABASE_URL: postgres://user:1234@postgres-test:5432/dev
    depends_on:
      - postgres-dev

volumes:
  postgresdb:
    driver: local
