version: "3.6"

x-redis: &redis
  image: redis:latest
  ports:
    - 127.0.0.1:6379:6379
  restart: always

x-postgres: &postgres
  image: postgres:latest
  ports:
    - 127.0.0.1:5432:5432

x-pgadmin: &pgadmin
  image: dpage/pgadmin4
  ports:
    - 127.0.0.1:5050:80
  environment:
    PGADMIN_DEFAULT_EMAIL: admin@admin.com
    PGADMIN_DEFAULT_PASSWORD: root

x-hasura: &hasura
  image: hasura/graphql-engine:v2.22.0
  ports:
    - 127.0.0.1:8080:8080
  restart: always

services:
  redis-test:
    <<: *redis
    profiles: ["test", "all"]
    command: redis-server --requirepass test-redis-passwd

  redis-dev:
    <<: *redis
    profiles: ["dev", "all"]
    command: redis-server --requirepass dev-redis-passwd

  postgres-test:
    <<: *postgres
    profiles: ["test", "all"]
    environment:
      POSTGRES_DB: 'test'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: '1234'

  postgres-dev:
    <<: *postgres
    profiles: ["dev", "all"]
    environment:
      POSTGRES_DB: 'dev'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: '1234'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - postgresdb:/var/lib/postgresql/data

  pgadmin-test:
    <<: *pgadmin
    profiles: ["test-gui", "all"]
    depends_on:
      - postgres-test

  pgadmin-dev:
    <<: *pgadmin
    profiles: ["dev-gui", "all"]
    depends_on:
      - postgres-dev

  hasura-test:
    <<: *hasura
    profiles: ["test", "all"]
    environment:
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DATABASE_URL: postgres://user:1234@postgres-test:5432/test
      PG_DATABASE_URL: postgres://user:1234@postgres-test:5432/test
    depends_on:
      - postgres-test

  hasura-dev:
    <<: *hasura
    profiles: ["dev", "all"]
    environment:
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DATABASE_URL: postgres://user:1234@postgres-test:5432/dev
      PG_DATABASE_URL: postgres://user:1234@postgres-test:5432/dev
    depends_on:
      - postgres-dev

volumes:
  postgresdb:
    driver: local
