name: Benchmark Test on Manual

on:
  workflow_dispatch:

jobs:
  test:
    name: Benchmark Testing
    strategy:
      matrix:
        node-version: ['lts/hydrogen']
        os: [ubuntu-latest]
        typescript-version: [4.2]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Install Docker
        # uses: docker-practice/actions-setup-docker@master
        # docker-practice/actions-setup-docker@master waiting for PR
        # REF: https://github.com/docker-practice/actions-setup-docker/pull/33
        uses: DimosthenisK/actions-setup-docker@fc48ecc37a6c3fe57342c08b4bc548926a27aa4a
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      
      - name: Install Yarn
        run: npm install -g yarn
      
      - name: Set resolutions to correct typescript version
        uses: jossef/action-set-json-field@v2
        with:
          file: package.json
          field: resolutions
          value: "{ \"typescript\": \"${{ matrix.typescript-version }}\"}"
          parse_json: true
      
      - name: Install
        # bcrypt depends on post-scripts since --ignore-scripts flag will disable it.
        run: |
          yarn add bcrypt
          yarn install --ignore-scripts --netwrok-timeout 100000
          curl -L https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh | bash

      - name: Output ts version
        run: yarn tsc --version

      - name: Output packages version
        run: yarn list

      - name: Hasura Cli version
        run: hasura version

      - name: Build Docker Stack
        run: docker-compose --profile test -f docker-compose.yml up -d

      - name: Docker status
        run: |
          sleep 5s
          docker ps -a

      - name: Dump DB structure from hasura migrations & seeds
        run: |
          hasura migrate apply --endpoint http://localhost:8080 --database-name default --project migrations/hasura --skip-update-check
          hasura seed apply --endpoint http://localhost:8080 --database-name default --project migrations/hasura --skip-update-check
      
      - name: Benchmark Testing
        run: yarn run test:benchmark --runInBand
